paths:
  # CSV used for training/validation
  csv_path: /home/nexus/VQ_PMCnmpc/VQ_PMC/logs/datasets/dataset_nmpc.csv
  # Base directory for run artifacts (model, scalers, plots, snapshot)
  base_save_dir: trained_models

training_params:
  # Training hyperparameters
  epochs: 1000
  batch_size: 64
  learning_rate: 1.0e-05
  val_split: 0.3

model_params:
  # Model architecture
  input_dim: 5
  output_dim: 3
  hidden_layers:
    - 1024
    - 1024
    - 1024
    - 1024
    - 1024
    - 1024
    - 1024
    - 1024
    - 1024
  p_dropout: 0.3
