paths:
  csv_path: /home/nexus/VQ_PMCnmpc/VQ_PMC/logs/datasets/dataset_nmpc.csv
  base_save_dir: trained_models
training_params:
  epochs: 1000
  batch_size: 64
  learning_rate: 1.0e-05
  val_split: 0.3
model_params:
  input_dim: 5
  output_dim: 3
  hidden_layers:
  - 1024
  - 1024
  - 1024
  - 1024
  - 1024
  - 1024
  - 1024
  - 1024
  - 1024
  p_dropout: 0.3
