# parameters.yaml
# Global configuration for training the MLP dynamics model.

paths:
  # Path to the dataset CSV used for training/validation
  csv_path: /home/nexus/VQ_PMCnmpc/VQ_PMC/logs/datasets/dataset_nmpc.csv
  # Base directory where run artifacts (model, scalers, plots, snapshot) will be stored
  base_save_dir: trained_models

training_params:
  # Number of training epochs
  epochs: 300
  # Batch size for DataLoader
  batch_size: 64
  # Learning rate for Adam
  learning_rate: 1.0e-05
  # Validation split ratio (episode-based split)
  val_split: 0.3
  # Number of history steps in the input window
  history_length: 3

model_params:
  # Hidden layer sizes
  hidden_layers:
    - 256
    - 256
    - 256
    - 256
  # Dropout probability (0.0 disables Dropout)
  p_dropout: 0.3
